name: hello_ddd
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Annotations
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Core packages
  dartz: ^0.10.1
  uuid: ^3.0.6
  intl: ^0.17.0
  shared_preferences: ^2.2.0
  http: ^1.1.0

  # Routing
  auto_route: ^7.5.0
  url_launcher: ^6.1.10

  # Bloc
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1

  # UI
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  flutter_datetime_picker_bdaya: ^3.0.2
  flutter_rating_bar: ^4.0.1
  expandable: ^5.0.1
  chips_choice: ^3.0.0
  another_flushbar: ^1.12.29

  # Firebase
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.8.1
  google_sign_in: ^6.1.0

  # Dependency injection
  get_it: ^7.2.0
  injectable: ^2.1.0

  # Bells and whistles
  rxdart: ^0.27.7
  flutter_hooks: ^0.18.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  freezed: ^2.3.2


  injectable_generator: ^2.1.3
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.1.1

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"